version: '3.8'

services:
  motherduck-db:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null  # コンテナが常駐するようにする
    container_name: motherduck-db-container
    volumes:
      - ./data:/data
    ports:
      - "8888:8888"
    environment:
      - PYTHONUNBUFFERED=1
